/**
 * ORION Multi-Language System v2
 * Hover dropdown, inline translations, no external files
 */
(function() {
  const LANG_KEY = 'orion_lang';
  const t = {
    en: {"nav_home":"Home","nav_products":"Products","nav_about":"About Us","nav_odm":"OEM/ODM","nav_blog":"Blog","nav_contact":"Contact","nav_quote":"Email Us","hero_badge":"OEM/ODM Manufacturing Partner","hero_title":"Your Trusted OEM Partner for SSD & Memory","hero_desc":"13+ years of OEM/ODM expertise. Custom branding, firmware, and packaging.","hero_quote":"Email Us","hero_products":"OEM Capabilities","section_products":"Product Categories","section_products_t":"Storage Solutions","section_products_d":"SSDs and memory for every need","cat_nvme":"NVMe SSDs","cat_nvme_d":"PCIe 4.0, 256GB-2TB, OEM ready","cat_sata":"SATA SSDs","cat_sata_d":"2.5-inch, 120GB-1.92TB, OEM","cat_memory":"Memory Modules","cat_memory_d":"DDR4/DDR5, desktop & laptop, OEM","cat_odm":"OEM/ODM Services","cat_odm_d":"Custom branding, firmware, packaging","features_t":"Why Partners Choose ORION","feat1_t":"Custom Branding","feat1_d":"Your logo on every drive","feat2_t":"Full OEM/ODM","feat2_d":"Custom PCB, firmware, packaging","stats_t":"By the Numbers","stat1":"13+ Years","stat1_l":"Industry","stat2":"50M+","stat2_l":"Units","stat3":"500+","stat3_l":"Clients","stat4":"10,000m2","stat4_l":"Factory","process_t":"OEM/ODM Process","process1":"Inquiry","process1_d":"Tell us requirements","process2":"Quote","process2_d":"24hr pricing","process3":"Production","process3_d":"Strict QC","process4":"Delivery","process4_d":"Packaging & shipping","cert_t":"Certifications","cert_t2":"Quality & Compliance","cert_d":"Fully certified for global markets","testimonial_t":"What Partners Say","cta_t":"Start Your OEM Project?","cta_d":"Get a quote within 24 hours","cta_btn":"Send Email","stat_years":"13+ Years","stat_years_l":"Industry Experience","stat_units":"50M+","stat_units_l":"Units Shipped","stat_clients":"500+","stat_clients_l":"B2B Partners","stat_countries":"50+","stat_countries_l":"Export Markets","stat1_l":"Industry","stat2_l":"Units","stat3_l":"Clients","stat4_l":"Factory","footer_products":"Products","footer_company":"Company","footer_contact":"Contact","footer_prod1":"NVMe SSDs","footer_prod2":"SATA SSDs","footer_prod3":"Memory","footer_prod4":"Industrial","footer_prod5":"OEM/ODM","footer_about":"About Us","footer_factory":"Factory","footer_cert":"Certifications","footer_blog":"Blog","footer_rights":"All rights reserved"},
    zh: {"nav_home":"棣栭〉","nav_products":"浜у搧涓績","nav_about":"鍏充簬鎴戜滑","nav_odm":"OEM/ODM","nav_blog":"鍗氬","nav_contact":"鑱旂郴鎴戜滑","nav_quote":"鍙戦€侀偖浠?,"hero_badge":"OEM/ODM鍒堕€犲悎浣滀紮浼?,"hero_title":"鍊煎緱淇¤禆鐨凷SD涓庡唴瀛極EM鍚堜綔浼欎即","hero_desc":"13骞翠互涓奜EM/ODM缁忛獙锛屾敮鎸佸畾鍒跺搧鐗屻€佸浐浠躲€佸寘瑁呫€?,"hero_quote":"鍙戦€侀偖浠?,"hero_products":"OEM鑳藉姏","section_products":"浜у搧绫诲埆","section_products_t":"瀛樺偍瑙ｅ喅鏂规","section_products_d":"婊¤冻鍚勭闇€姹傜殑SSD涓庡唴瀛?,"cat_nvme":"NVMe鍥烘€佺‖鐩?,"cat_nvme_d":"PCIe 4.0锛?56GB-2TB锛孫EM灏辩华","cat_sata":"SATA鍥烘€佺‖鐩?,"cat_sata_d":"2.5鑻卞锛?20GB-1.92TB锛孫EM","cat_memory":"鍐呭瓨妯＄粍","cat_memory_d":"DDR4/DDR5锛屽彴寮忓強绗旇鏈紝OEM","cat_odm":"OEM/ODM鏈嶅姟","cat_odm_d":"瀹氬埗鍝佺墝銆佸浐浠躲€佸寘瑁?,"features_t":"涓轰粈涔堥€夋嫨ORION","feat1_t":"瀹氬埗鍝佺墝","feat1_d":"姣忛纭洏閮芥湁鎮ㄧ殑鍝佺墝","feat2_t":"瀹屾暣OEM/ODM","feat2_d":"瀹氬埗PCB銆佸浐浠躲€佸寘瑁?,"stats_t":"鏁版嵁璇磋瘽","stat1":"13+骞?,"stat1_l":"琛屼笟缁忛獙","stat2":"5000涓?","stat2_l":"鍑鸿揣閲?,"stat3":"500+","stat3_l":"瀹㈡埛","stat4":"1涓噈2","stat4_l":"宸ュ巶","process_t":"OEM/ODM娴佺▼","process1":"闇€姹傛矡閫?,"process1_d":"鍛婅瘔鎴戜滑闇€姹?,"process2":"鎶ヤ环鎵撴牱","process2_d":"24灏忔椂鎶ヤ环","process3":"鎵归噺鐢熶骇","process3_d":"涓ユ牸鍝佹帶","process4":"鐗╂祦浜や粯","process4_d":"鍖呰涓庣墿娴?,"cert_t":"璁よ瘉璧勮川","cert_t2":"璐ㄩ噺涓庡悎瑙?,"cert_d":"鍏ㄧ郴鍒椾骇鍝佽幏寰楀叏鐞冭璇?,"testimonial_t":"鍚堜綔浼欎即璇勪环","cta_t":"寮€濮婳EM椤圭洰锛?,"cta_d":"24灏忔椂鍐呰幏鍙栨姤浠?,"cta_btn":"鍙戦€侀偖浠?,"stat_years":"13+骞?,"stat_years_l":"琛屼笟缁忛獙","stat_units":"5000涓?","stat_units_l":"鍑鸿揣閲?,"stat_clients":"500+","stat_clients_l":"B2B瀹㈡埛","stat_countries":"50+","stat_countries_l":"鍑哄彛甯傚満","footer_products":"浜у搧","footer_company":"鍏徃","footer_contact":"鑱旂郴","footer_prod1":"NVMe鍥烘€佺‖鐩?,"footer_prod2":"SATA鍥烘€佺‖鐩?,"footer_prod3":"鍐呭瓨","footer_prod4":"宸ヤ笟绾?,"footer_prod5":"OEM/ODM","footer_about":"鍏充簬鎴戜滑","footer_factory":"宸ュ巶","footer_cert":"璁よ瘉","footer_blog":"鍗氬","footer_rights":"鐗堟潈鎵€鏈?},
    es: {"nav_home":"Inicio","nav_products":"Productos","nav_about":"Nosotros","nav_odm":"OEM/ODM","nav_blog":"Blog","nav_contact":"Contacto","nav_quote":"Email","hero_quote":"Email","hero_products":"Capacidades OEM","features_t":"Por qu茅 elegir ORION","cta_t":"驴Listo para su proyecto OEM?","cta_d":"Reciba un presupuesto en 24h","cta_btn":"Enviar Email","footer_products":"Productos","footer_company":"Empresa","footer_contact":"Contacto","footer_about":"Sobre nosotros","footer_blog":"Blog","footer_rights":"Todos los derechos reservados"},
    fr: {"nav_home":"Accueil","nav_products":"Produits","nav_about":"脌 propos","nav_odm":"OEM/ODM","nav_blog":"Blog","nav_contact":"Contact","nav_quote":"Email","hero_quote":"Email","hero_products":"Services OEM","features_t":"Pourquoi ORION","cta_t":"Pr锚t pour votre projet OEM?","cta_d":"Devis sous 24h","cta_btn":"Envoyer un Email","footer_products":"Produits","footer_company":"Soci茅t茅","footer_contact":"Contact","footer_about":"脌 propos","footer_blog":"Blog","footer_rights":"Tous droits r茅serv茅s"},
    pt: {"nav_home":"In铆cio","nav_products":"Produtos","nav_about":"Sobre","nav_odm":"OEM/ODM","nav_blog":"Blog","nav_contact":"Contato","nav_quote":"Email","hero_quote":"Email","hero_products":"Servi莽os OEM","features_t":"Por que escolher ORION","cta_t":"Pronto para seu projeto OEM?","cta_d":"Or莽amento em 24h","cta_btn":"Enviar Email","footer_products":"Produtos","footer_company":"Empresa","footer_contact":"Contato","footer_about":"Sobre","footer_blog":"Blog","footer_rights":"Todos os direitos reservados"},de:{"nav_home":"Start","nav_products":"Produkte","nav_about":"脺ber uns","nav_odm":"OEM/ODM","nav_blog":"Blog","nav_contact":"Kontakt","nav_quote":"E-Mail","prod_hero":"Unser Sortiment","about_hero":"脺ber ORION","odm_hero":"OEM/ODM Dienstleistungen","contact_hero":"Kontakt","cta_btn":"E-Mail senden"},nl:{"nav_home":"Home","nav_products":"Producten","nav_about":"Over ons","nav_odm":"OEM/ODM","nav_blog":"Blog","nav_contact":"Contact","nav_quote":"E-mail","prod_hero":"Ons assortiment","about_hero":"Over ORION","odm_hero":"OEM/ODM Diensten","contact_hero":"Contact","cta_btn":"E-mail sturen"},it:{"nav_home":"Home","nav_products":"Prodotti","nav_about":"Chi siamo","nav_odm":"OEM/ODM","nav_blog":"Blog","nav_contact":"Contatto","nav_quote":"Email","prod_hero":"I nostri prodotti","about_hero":"Chi siamo","odm_hero":"Servizi OEM/ODM","contact_hero":"Contatto","cta_btn":"Invia email"}
  };

  function getLang() { return localStorage.getItem(LANG_KEY) || 'en'; }
  function setLang(l) { localStorage.setItem(LANG_KEY, l); document.documentElement.lang = l; }

  window.switchLang = function(lang) {
    if (!t[lang]) return;
    setLang(lang);
    const dict = t[lang];
    document.querySelectorAll('[data-i]').forEach(el => {
      const k = el.dataset.i;
      if (dict[k] !== undefined) el.textContent = dict[k];
    });
    // Update active in dropdown
    document.querySelectorAll('.lang-item').forEach(a => a.classList.toggle('active', a.dataset.lang === lang));
  };

  document.addEventListener('DOMContentLoaded', function() {
    const nav = document.querySelector('.nav-menu');
    if (!nav) return;
    const li = document.createElement('li');
    li.style.cssText = 'margin-left:8px';
    li.className = 'lang-hover-wrap';
    li.innerHTML = '<div class="lang-hover"><button class="lang-btn" onclick="event.stopPropagation()">馃寪</button><div class="lang-dropdown-content">' +
      '<a class="lang-item" data-lang="en" onclick="switchLang(\'en\')">馃嚞馃嚙 English</a>' +
      '<a class="lang-item" data-lang="zh" onclick="switchLang(\'zh\')">馃嚚馃嚦 涓枃</a>' +
      '<a class="lang-item" data-lang="es" onclick="switchLang(\'es\')">馃嚜馃嚫 Espa帽ol</a>' +
      '<a class="lang-item" data-lang="fr" onclick="switchLang(\'fr\')">馃嚝馃嚪 Fran莽ais</a>' +
      '<a class="lang-item" data-lang="pt" onclick="switchLang(\'pt\')">馃嚙馃嚪 Portugu锚s</a>' +
      '<a class="lang-item" data-lang="de" onclick="switchLang(\'de\')">馃嚛馃嚜 Deutsch</a>' +
      '<a class="lang-item" data-lang="nl" onclick="switchLang(\'nl\')">馃嚦馃嚤 Nederlands</a>' +
      '<a class="lang-item" data-lang="it" onclick="switchLang(\'it\')">馃嚠馃嚬 Italiano</a>' +
      '</div></div>';
    nav.appendChild(li);
    // Apply current language
    switchLang(getLang());
  });
})();,"feat3_t":"Black 10-Layer PCB","feat3_d":"Premium quality boards","feat4_t":"Complete Certification","feat4_d":"CE, FCC, ROHS, REACH","feat5_t":"Quality Assurance","feat5_d":"100% burn-in test, 3-year warranty","feat6_t":"Flexible MOQ","feat6_d":"From 100 units","prod_e100_s":"256GB-2TB, 5000MB/s","prod_e200_s":"512GB-4TB, 7450MB/s","prod_e300_s":"256GB-1TB, Budget","prod_s100_s":"120GB-1.92TB, 550MB/s","prod_s200_s":"480GB-3.84TB, Enterprise","prod_ddr5_s":"8-32GB, DDR5-7200","prod_ddr4_s":"4-32GB, DDR4-3600","prod_ind_s":"32GB-512GB, Industrial","prod_oem_s":"Custom OEM/ODM","about_story_t":"Our Story","about_story1":"Industry since 2013","about_story2":"SSD R&D and manufacturing","about_story3":"Global OEM/ODM partner","odm_white_label":"White label OEM","odm_custom":"Custom ODM design","odm_joint":"Joint development"}


